### ISSUE TITLE
Welcome to SEBC

### ISSUE THREAD

**Issue by mfernest** [junhou/SEBC#1]
Your repository setup appears complete and correct -- good job!

Please email me at mfe@cloudera with your name so I know how to address you in class.

Once the co-instructors have accepted your invitations to collaborate, you may close this issue.

**Comment by junhou** [comment]
mfe@cloudera looks like not an valid email address.

**Comment by mfernest** [comment]
Apologies, it should have been `mfe@cloudera.com`
